No `extern "C"` main functions (IREE-20223)
A user is reporting a build failure with top-of-tree Clang:

https://discourse.llvm.org/t/build-error-of-iree-may-related-to-clang21/85090

> iree/tools/iree-check-module-main.cc:150:16: error: ‘main’ should not
be ‘extern “C”’ [-Werror,-Wmain]

Clang is correct: `main` really can't be `extern "C"`:
https://eel.is/c++draft/basic.start#main-2

> Its type shall have C++ language linkage

Anyway, what was the reason for `extern "C"` ?

---------

Signed-off-by: Benoit Jacob <jacob.benoit.1@gmail.com>