Relax assert in task_worker_deinitialize in case thread creation failed (IREE-22689)
Currently if thread creation fails, NULL thread causes await_exit to
pass through without updating the thread status, causing us to hit an
assert for a non-zombie thread on deinitialize.
iree_task_worker_initialize notes that failures to init are intended to
go through deinitialize, but the assert leads to confusing error output.
Relaxing the assert produces the expected status failure, e.g.

```
RuntimeError: Error creating driver: ../iree/runtime/src/iree/base/internal/threading_pthreads.c:176: INTERNAL; thread creation failed with 22
```